
online: true

logging.config: classpath:log-prod.xml

spring.application.name: task

register.center: http://prod1:8761/eureka/,http://prod2:8761/eureka/,http://prod3:8761/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
