
online: false

server.port: 8072

spring.application.name: search

spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

logging.config: classpath:log-test.xml

spring.datasource:
  url: jdbc:mysql://test_search_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
  username: test_search_user
  password: test_search_pass
  hikari:
    minimumIdle: 2
    maximumPoolSize: 5
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true

register.center: http://test1:8761/eureka/,http://test2:8761/eureka/,http://test3:8761/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

#spring:
#  zipkin.base-url: http://127.0.0.1:9411
#  sleuth.sampler.percentage: 0.1
