
# 开发环境

online: false

logging.config: classpath:log-dev.xml

spring.application.name: queue-consume


spring:
  activemq:
    broker-url: failover:(tcp://ip:port)?timeout=3000&startupMaxReconnectAttempts=5
    user: admin
    password: admin


register.center: http://127.0.0.1:8761/eureka/
eureka:
  client:
    # 开启健康检查(需要 spring-boot-starter-actuator 包)
    healthcheck.enabled: true
    # 客户端间隔多久去拉取服务注册信息, 默认为 30 秒
    registry-fetch-interval-seconds: 20
    serviceUrl.defaultZone: ${register.center}
  instance:
    # 客户端发送心跳给注册中心的频率, 默认 30 秒
    lease-renewal-interval-in-seconds: 20
    # 服务端在收到最后一个心跳后的等待时间. 超出将摘除该实例, 默认 90 秒, 此值至少要大于 lease-renewal-interval-in-seconds
    lease-expiration-duration-in-seconds: 60
